name: Make subgraphs never die

on:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 16.13
    - run: npm install
    # Run script
    - name: Make subgraphs never die
      run: |-
        node script.js